# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ui_flightInspector.ui'
#
# Created by: PyQt5 UI code generator 5.5
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtWidgets

class Ui_flightInspector(object):
    def setupUi(self, flightInspector):
        flightInspector.setObjectName("flightInspector")
        flightInspector.resize(313, 857)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(flightInspector.sizePolicy().hasHeightForWidth())
        flightInspector.setSizePolicy(sizePolicy)
        self.verticalLayout = QtWidgets.QVBoxLayout(flightInspector)
        self.verticalLayout.setObjectName("verticalLayout")
        self.gridLayout = QtWidgets.QGridLayout()
        self.gridLayout.setObjectName("gridLayout")
        self.label_4 = QtWidgets.QLabel(flightInspector)
        self.label_4.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.label_4.setObjectName("label_4")
        self.gridLayout.addWidget(self.label_4, 2, 0, 1, 1)
        self.label_stand = QtWidgets.QLabel(flightInspector)
        self.label_stand.setFrameShape(QtWidgets.QFrame.Box)
        self.label_stand.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.label_stand.setText("")
        self.label_stand.setObjectName("label_stand")
        self.gridLayout.addWidget(self.label_stand, 3, 1, 1, 1)
        self.label_time = QtWidgets.QLabel(flightInspector)
        self.label_time.setFrameShape(QtWidgets.QFrame.Box)
        self.label_time.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.label_time.setText("")
        self.label_time.setObjectName("label_time")
        self.gridLayout.addWidget(self.label_time, 6, 1, 1, 1)
        self.label_qfu = QtWidgets.QLabel(flightInspector)
        self.label_qfu.setFrameShape(QtWidgets.QFrame.Box)
        self.label_qfu.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.label_qfu.setText("")
        self.label_qfu.setObjectName("label_qfu")
        self.gridLayout.addWidget(self.label_qfu, 5, 1, 1, 1)
        self.label_6 = QtWidgets.QLabel(flightInspector)
        self.label_6.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.label_6.setObjectName("label_6")
        self.gridLayout.addWidget(self.label_6, 6, 0, 1, 1)
        self.label_8 = QtWidgets.QLabel(flightInspector)
        self.label_8.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.label_8.setObjectName("label_8")
        self.gridLayout.addWidget(self.label_8, 4, 0, 1, 1)
        self.label_callsign = QtWidgets.QLabel(flightInspector)
        self.label_callsign.setFrameShape(QtWidgets.QFrame.Box)
        self.label_callsign.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.label_callsign.setText("")
        self.label_callsign.setObjectName("label_callsign")
        self.gridLayout.addWidget(self.label_callsign, 0, 1, 1, 1)
        self.label_runway = QtWidgets.QLabel(flightInspector)
        self.label_runway.setFrameShape(QtWidgets.QFrame.Box)
        self.label_runway.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.label_runway.setText("")
        self.label_runway.setObjectName("label_runway")
        self.gridLayout.addWidget(self.label_runway, 4, 1, 1, 1)
        self.label_2 = QtWidgets.QLabel(flightInspector)
        self.label_2.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.label_2.setObjectName("label_2")
        self.gridLayout.addWidget(self.label_2, 1, 0, 1, 1)
        self.label_wake = QtWidgets.QLabel(flightInspector)
        self.label_wake.setFrameShape(QtWidgets.QFrame.Box)
        self.label_wake.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.label_wake.setText("")
        self.label_wake.setObjectName("label_wake")
        self.gridLayout.addWidget(self.label_wake, 2, 1, 1, 1)
        self.label = QtWidgets.QLabel(flightInspector)
        self.label.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.label.setObjectName("label")
        self.gridLayout.addWidget(self.label, 0, 0, 1, 1)
        self.label_7 = QtWidgets.QLabel(flightInspector)
        self.label_7.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.label_7.setObjectName("label_7")
        self.gridLayout.addWidget(self.label_7, 5, 0, 1, 1)
        self.label_movement_type = QtWidgets.QLabel(flightInspector)
        self.label_movement_type.setFrameShape(QtWidgets.QFrame.Box)
        self.label_movement_type.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.label_movement_type.setText("")
        self.label_movement_type.setObjectName("label_movement_type")
        self.gridLayout.addWidget(self.label_movement_type, 1, 1, 1, 1)
        self.label_3 = QtWidgets.QLabel(flightInspector)
        self.label_3.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.label_3.setObjectName("label_3")
        self.gridLayout.addWidget(self.label_3, 3, 0, 1, 1)
        self.label_5 = QtWidgets.QLabel(flightInspector)
        self.label_5.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.label_5.setObjectName("label_5")
        self.gridLayout.addWidget(self.label_5, 7, 0, 1, 1)
        self.label_slot = QtWidgets.QLabel(flightInspector)
        self.label_slot.setFrameShape(QtWidgets.QFrame.Box)
        self.label_slot.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.label_slot.setText("")
        self.label_slot.setObjectName("label_slot")
        self.gridLayout.addWidget(self.label_slot, 7, 1, 1, 1)
        self.verticalLayout.addLayout(self.gridLayout)
        self.frame = QtWidgets.QFrame(flightInspector)
        self.frame.setFrameShape(QtWidgets.QFrame.Box)
        self.frame.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.frame.setObjectName("frame")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.frame)
        self.verticalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_2.setSpacing(0)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.label_9 = QtWidgets.QLabel(self.frame)
        self.label_9.setObjectName("label_9")
        self.verticalLayout_2.addWidget(self.label_9)
        self.frame_4 = QtWidgets.QFrame(self.frame)
        self.frame_4.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.frame_4.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_4.setObjectName("frame_4")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout(self.frame_4)
        self.horizontalLayout_3.setContentsMargins(5, 5, 5, 5)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.label_12 = QtWidgets.QLabel(self.frame_4)
        self.label_12.setObjectName("label_12")
        self.horizontalLayout_3.addWidget(self.label_12)
        self.radioButton_slot = QtWidgets.QRadioButton(self.frame_4)
        self.radioButton_slot.setObjectName("radioButton_slot")
        self.horizontalLayout_3.addWidget(self.radioButton_slot)
        self.radioButton_noslot = QtWidgets.QRadioButton(self.frame_4)
        self.radioButton_noslot.setObjectName("radioButton_noslot")
        self.horizontalLayout_3.addWidget(self.radioButton_noslot)
        self.radioButton_slotornot = QtWidgets.QRadioButton(self.frame_4)
        self.radioButton_slotornot.setChecked(True)
        self.radioButton_slotornot.setObjectName("radioButton_slotornot")
        self.horizontalLayout_3.addWidget(self.radioButton_slotornot)
        self.verticalLayout_2.addWidget(self.frame_4)
        self.frame_2 = QtWidgets.QFrame(self.frame)
        self.frame_2.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.frame_2.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_2.setObjectName("frame_2")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.frame_2)
        self.horizontalLayout.setContentsMargins(5, 5, 5, 5)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.label_11 = QtWidgets.QLabel(self.frame_2)
        self.label_11.setObjectName("label_11")
        self.horizontalLayout.addWidget(self.label_11)
        self.comboBox_type = QtWidgets.QComboBox(self.frame_2)
        self.comboBox_type.setObjectName("comboBox_type")
        self.horizontalLayout.addWidget(self.comboBox_type)
        self.verticalLayout_2.addWidget(self.frame_2)
        self.frame_3 = QtWidgets.QFrame(self.frame)
        self.frame_3.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.frame_3.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_3.setObjectName("frame_3")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.frame_3)
        self.horizontalLayout_2.setContentsMargins(5, 5, 5, 5)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.label_10 = QtWidgets.QLabel(self.frame_3)
        self.label_10.setObjectName("label_10")
        self.horizontalLayout_2.addWidget(self.label_10)
        self.comboBox_runway = QtWidgets.QComboBox(self.frame_3)
        self.comboBox_runway.setObjectName("comboBox_runway")
        self.horizontalLayout_2.addWidget(self.comboBox_runway)
        self.verticalLayout_2.addWidget(self.frame_3)
        self.frame_5 = QtWidgets.QFrame(self.frame)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.frame_5.sizePolicy().hasHeightForWidth())
        self.frame_5.setSizePolicy(sizePolicy)
        self.frame_5.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.frame_5.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_5.setObjectName("frame_5")
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout(self.frame_5)
        self.horizontalLayout_4.setContentsMargins(5, 5, 5, 5)
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.label_13 = QtWidgets.QLabel(self.frame_5)
        self.label_13.setObjectName("label_13")
        self.horizontalLayout_4.addWidget(self.label_13)
        self.lineEdit_callsign = QtWidgets.QLineEdit(self.frame_5)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lineEdit_callsign.sizePolicy().hasHeightForWidth())
        self.lineEdit_callsign.setSizePolicy(sizePolicy)
        self.lineEdit_callsign.setObjectName("lineEdit_callsign")
        self.horizontalLayout_4.addWidget(self.lineEdit_callsign)
        self.verticalLayout_2.addWidget(self.frame_5)
        self.verticalLayout.addWidget(self.frame)
        self.list_flights = QtWidgets.QListWidget(flightInspector)
        self.list_flights.setObjectName("list_flights")
        self.verticalLayout.addWidget(self.list_flights)

        self.retranslateUi(flightInspector)
        QtCore.QMetaObject.connectSlotsByName(flightInspector)

    def retranslateUi(self, flightInspector):
        _translate = QtCore.QCoreApplication.translate
        flightInspector.setWindowTitle(_translate("flightInspector", "Flight Inspector"))
        self.label_4.setText(_translate("flightInspector", "Wake vortex category"))
        self.label_6.setText(_translate("flightInspector", "Beginning time"))
        self.label_8.setText(_translate("flightInspector", "Used runway"))
        self.label_2.setText(_translate("flightInspector", "Movement type"))
        self.label.setText(_translate("flightInspector", "Callsign"))
        self.label_7.setText(_translate("flightInspector", "Used QFU"))
        self.label_3.setText(_translate("flightInspector", "Used stand"))
        self.label_5.setText(_translate("flightInspector", "CFMU slot"))
        self.label_9.setText(_translate("flightInspector", "Filter flight list by:"))
        self.label_12.setText(_translate("flightInspector", "Slot"))
        self.radioButton_slot.setText(_translate("flightInspector", "With slot"))
        self.radioButton_noslot.setText(_translate("flightInspector", "Without slot"))
        self.radioButton_slotornot.setText(_translate("flightInspector", "All"))
        self.label_11.setText(_translate("flightInspector", "Type"))
        self.label_10.setText(_translate("flightInspector", "Runway"))
        self.label_13.setText(_translate("flightInspector", "Callsign contains..."))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    flightInspector = QtWidgets.QWidget()
    ui = Ui_flightInspector()
    ui.setupUi(flightInspector)
    flightInspector.show()
    sys.exit(app.exec_())

